//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendEdgeWebService.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public Nullable<System.DateTime> BreakInTime { get; set; }
        public Nullable<System.DateTime> BreakOutTime { get; set; }
        public decimal LatitudeCheckIn { get; set; }
        public decimal LongitudeCheckIn { get; set; }
        public Nullable<decimal> LatitudeCheckOut { get; set; }
        public Nullable<decimal> LongitudeCheckOut { get; set; }
        public Nullable<decimal> LatitudeBreakIn { get; set; }
        public Nullable<decimal> LongitudeBreakIn { get; set; }
        public Nullable<decimal> LatitudeBreakOut { get; set; }
        public Nullable<decimal> LongitudeBreakOut { get; set; }
        public string CheckInImagePath { get; set; }
        public string CheckOutImagePath { get; set; }
        public string BreakInImagePath { get; set; }
        public string BreakOutImagePath { get; set; }
        public string LocationDescription { get; set; }
        public string DeviceInfo { get; set; }
        public string IPAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
